[project]
name = "clams-tool-shack"
version = "0.1.0"
description = "ClamShack tool for running CLAMS applications and managing resulting MMIF files"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "clams-utils>=251011",
    "dotenv>=0.9.9",
    "flask==2.*",
    #"inspector-mv",
    "mmif-python==1.4.*",
    "rich>=15.0.0",
]

#[tool.uv.sources]
#inspector-mv = { path = "packages/inspector_mv-0.0.3.tar.gz" }

#[dependency-groups]
#dev = [
#    "pytest>=9.0.2",
#]
